codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project: # Overall project coverage
      default:
        target: 90%    # the required coverage value
        threshold: 5%  # the leniency in hitting the target
    patch: # Patch coverage 
      default:
        target: 80%
        threshold: 10%
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - tests/**/*
