name: codecov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Coverage report
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coverage
        pip install -r .github/.manifest/requirements.txt
        pip install -e .
    - name: Run tests and collect coverage
      run: pytest --benchmark-skip --cov --cov-report xml .
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2