name: actions pytest benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        fetch-depth: 2
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coverage
        pip install -r .manifest/requirements.txt
        pip install -e .
    
    - name: Benchmark previous commit
     run: |
        git checkout HEAD^
        coverage run -m pytest --benchmark-only --benchmark-save=GH_actions 

    - name: Compare benchmark with current commit
      run: |
        git checkout HEAD 
        coverage run -m pytest --benchmark-only --benchmark-save=GH_actions --benchmark-compare --benchmark-compare-fail=min:5%
